// quizData.js
export const quizQuestions = [
    {
      question: 'อะไรคือจุดแข็งที่ยิ่งใหญ่ที่สุดของคุณ?',
      choices: [
        'Your magnetic personality (บุคลิกภาพที่น่าดึงดูด)',
        'Compassion (ความเห็นอกเห็นใจ)',
        'Relating to others (การสร้างความสัมพันธ์กับผู้อื่น)',
        'Positive thinking (มองโลกในแง่ดี)',
        'Empowering others (การเพิ่มขีดความสามารถให้กับผู้อื่น)',
        'Curiosity (ความอยากรู้)',
      ],
      style: [
        ['A', 'B'],
        ['A', 'B'],
        ['A', 'B'],
        ['A', 'B'],
        ['A', 'B'],
        ['A', 'B'],
      ],
    },
    {
      question:
        'ถ้าพูดถึงรูปลักษณ์ภายนอกสำคัญมากแค่ไหนสำหรับคุณ  (100% คือสำคัญมากที่สุด)',
      choices: ['100%', '70%', '50%'],
      style: [
        ['elegant', 'alluring', 'Dramatic'],
        ['Classic', 'elegant', 'Feminine'],
        ['Natural', 'Classic'],
      ],
    },
    {
      question: 'คุณสนใจเนื้อหาประเภทใดต่อไปนี้มากที่สุด',
      choices: [
        'วิธีที่ผู้คนมีความสัมพันธ์ที่ดีต่อกันได้',
        'ตัวอย่างและกรณีศึกษาของบุคคลหรือบริษัทที่ประสบความสำเร็จ',
        'หนังสือ งานวิจัย หรือ บทความ ที่มีความรู้',
        'เนื้อหาสร้างแรงบันดาลใจ',
        'ประสบการณ์ หรือเทคนิคใหม่ๆ ที่ต้องการให้ผู้ชมทดลองตาม',
        'การเปิดโปงอะไรบางอย่างที่ถูกซ่อนไว้เพื่อผลประโยชน์',
        'คอนเทนคลายเครียด บันเทิง และตลก',
      ],
      style: [
        ['Natural', 'Classic', 'Feminine'],
        ['elegant', 'alluring', 'Dramatic'],
        ['elegant'],
        ['elegant', 'Creative'],
        ['Creative'],
        ['Alluring', 'Creative', 'Drama'],
        ['Natural', 'Classic', 'Feminine'],
      ],
    },
    {
      question: 'เพื่อนมักจะบอกว่าคุณเป็นคนยังไง',
      choices: [
        'เป็นคนดูดีมีเสน่ห์ สวย หล่อ มีแรงดึงดูด',
        'เป็นผู้ให้ มีน้ำใจ ชอบคิดถึงคนอื่นก่อนเสมอ',
        'เป็นคนไม่ซับซ้อน เข้าใจทุกคน เข้ากับคนง่าย ปรับตัวง่ายกับทุกสถานการณ์',
        'เป็นคนมองโลกในแง่ดี ตรงไปตรงมา ไม่มีพิษมีภัย ',
        'เป็นคนมีรสนิยมที่ดี เป็นไอดอลของหลายๆคน ไว้ใจให้เป็นผู้นำในกลุ่ม ',
        'ผู้เชี่ยวชาญ เป็นคนช่างสังเกต ฉลาด รู้อะไรรู้จริง  นักวางแผน',
        'มีจินตนาการและสร้างสรรค์ที่คนอื่นมักจะไม่นึกถึง ทำในสิ่งที่คนอื่นทำไม่ได้ ',
        'กล้าคิดกล้าทำกล้าตัดสินใจ เป็นคนรักความยุติธรรม ภูมืใจในตัวเอง ไม่เคยหยุดนิ่ง',
        'ชอบหาประสบการณ์ใหม่ๆให้กับตัวเอง เป็นคนเดาใจยาก ',
        'เป็นคนมีจินตนาการ มีความคิดสร้างสรรค์ ทะเยอะทะยาน มีความเป็นตัวของตัวเองสูง',
        'รักอิสระ โผงผาง สุดโต่ง คิดต่าง ไม่ชอบถูกกำหนด และมีเงื่อนไข',
        'เป็นคนตลก สร้างบรรยากาศดีๆให้คนอื่นเสมอ ',
      ],
      type: [
        'The lover',
        'The caregiver',
        'The Everyman',
        'The innocent ',
        'The ruler',
        'The sage',
        'The magician',
        'The hero',
        'the explorer',
        'The creator',
        'The rebel',
        'The entertainer',
      ],
      typeid: [
        'The_lover',
        'The_caregiver',
        'The_Everyman',
        'The_innocent ',
        'The_ruler',
        'The_sage',
        'The_magician',
        'The_hero',
        'the_explorer',
        'The_creator',
        'The_rebel',
        'The_entertainer',
      ],
      style: [
        ['Classic', 'elegant', 'alluring', 'Dramatic'],
        ['Natural', 'Classic', 'Feminine'],
        ['Natural', 'Classic', 'Feminine'],
        ['Natural', 'Classic', 'elegant', 'Creative'],
        ['Classic', 'elegant', 'alluring', 'Dramatic'],
        ['Natural', 'Classic', 'elegant', 'Creative'],
        ['elegant', 'alluring', 'Creative', 'Dramatic'],
        ['Classic', 'elegant', 'alluring', 'Dramatic'],
        ['Natural', 'Classic', 'elegant', 'Dramatic'],
        ['Classic', 'elegant', 'alluring', 'Creative', 'Dramatic'],
        ['elegant', 'alluring', 'Creative', 'Dramatic'],
        ['Natural', 'Classic', 'elegant', 'creative'],
      ],
    },
    {
      question: 'อะไรเป็นจุดอ่อนของคุณ',
      choices: [
        'ไม่สามารถจัดการความต้องการและความรู้สึกของตัวเองได้',
        'คนรอบตัวไม่ค่อยมีความเกรงใจ ถูกข้ามเส้นบ่อยเกินไป ',
        'ไม่เป็นตัวของตัวเอง ไม่รู้ว่าตัวเองมีจุดเด่นด้านไหน',
        'ดูเข้าถึงยาก ไม่สามารถปฏิสัมพันธ์กับคนทั่วไปได้ง่าย',
        'ยากที่จะเข้าใจและรับฟังความคิดเห็น ของผู้อื่น',
        'ไม่ความมีวินัย และไม่สามารถจัดลำดับความสำคัญของชีวิตตัวเองได้ดี',
      ],
      style: [
        ['alluring', 'Dramatic'],
        ['Natural', 'Classic', 'Feminine'],
        ['Natural', 'Classic', 'Feminine'],
        ['Natural', 'Classic', 'Feminine'],
        ['elegant', 'alluring', 'Dramatic'],
        ['Classic', 'elegant', 'alluring', 'Creative'],
        ['Natural', 'Classic', 'Feminine', 'Dramatic'],
      ],
    },
    {
      question: 'อะไรเป็นเกณฑ์ในความสำคัญของการแต่งกายของคุณ ',
      choices: [
        'ความสวยงาม ',
        'ไม่ยุ่งยาก',
        'ความน่าเชื่อถือ',
        'สไตล์ที่บอกความเป็นตัวเอง ',
      ],
      style: [
        ['Natural', 'Classic', 'Feminine'],
        ['Natural', 'Classic'],
        ['Elegant'],
        ['Elegant', 'Creative', 'Alluring', 'Dramatic'],
      ],
    },
    {
      question: 'อีกครั้งนะครับ อะไรสำคัญที่สุดสำหรับการแต่งกายของคุณ',
      choices: [
        'น่าสนใจ น่าดึงดูด Attractive ',
        'เรียบร้อย ไม่โดดเด่นเกินไป ',
        'มีรสนิยม',
        'เรียบร้อย ไม่แตกต่างไม่แตกแยก',
        'แตกต่างไม่เหมือนใคร ',
      ],
      style: [
        ['Elegant', 'Creative', 'Feminine', 'Alluring', 'Dramatic'],
        ['Natural', 'Classic'],
        ['Classic', 'Elegant', 'Alluring'],
        ['Natural', 'Classic'],
        ['Creative', 'Alluring', 'Dramatic'],
      ],
    },
    {
      question: 'อยากให้คนจำเราในเรื่องไหนที่สุด ',
      choices: [
        'มีเสน่ห์ น่าหลงไหล',
        'เป็นคนใจดี มีเมตตา',
        'เป็นคน Friendly เข้าถึงได้',
        'เป็นคนมองโลกในแง่ดี ไม่มีพิษมีภัย',
        'เป็นผู้นำ เชื่อเชื่อถือ เป็น Role model ที่ดี',
        'น่าเชื่อถือ เป็นผู้เชี่ยวชาญ ผู้รู้ในสายงาน มีความรู้',
        'มีวิสัยทัศน์ที่ดี มีจินตนาการ',
        'เป็นนักสู้ รักความยุติธรรม เอาจริงเอาจัง ',
        'พึ่งพาตัวเองได้ กล้าคิดกล้าตัดสินใจ',
        'เป็นนักแก้ปัญหาเฉพาะหน้า และมีความ unique ไม่เหมือนใคร',
        'เป็นคนไม่ยึดติดกับกรอบเดิมๆ รักอิสระ ',
        'เป็นคนสนุก อารมณ์ดี เฮฮา',
      ],
      style: [
        ['1'],
        ['2'],
        ['3'],
        ['4'],
        ['5'],
        ['6'],
        ['7'],
        ['8'],
        ['9'],
        ['10'],
        ['11'],
        ['12'],
      ],
    },
    {
      question:
        'เลือกสไตล์เสื้อผ้าที่คุณชอบ หรือ รู้สึก มั่นใจเพื่อการพบเจอคน หรือการทำงาน',
      choices: ['มีชีวิตชีวา', 'สุขุม สงบ'],
      style: [
        ['Natural', 'Feminine', 'alluring', 'Creative', 'Dramatic'],
        ['Natural', 'Classic', 'elegant', 'alluring', 'Creative', 'Dramatic'],
      ],
    },
    {
      question: 'ความรู้สึกอยากให้คนอื่นรู้สึก',
      choices: ['สง่างาม', 'เป็นธรรมชาติ', 'แตกต่าง'],
      style: [
        ['Classic', 'Elegant', 'Alluring'],
        ['Natural', 'Classic', 'Elegant', 'Feminine'],
        ['Elegant', 'Creative', 'Alluring', 'Dramatic'],
      ],
    },
  ]
  